spring.application.name=api-gateway
server.port=6970
spring.cloud.gateway.mvc.http-client.connect-timeout=3000
spring.cloud.gateway.mvc.http-client.read-timeout=10000
eureka.client.service-url.defaultZone=http://localhost:6969/eureka
management.endpoints.web.exposure.include=gateway,health,info
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
springdoc.api-docs.path=/gateway/api-docs
springdoc.swagger-ui.enabled=false
