server.port=6971
spring.application.name=auth-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-manager
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:6969/eureka/
